#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: api
apiVersion: api.webmethods.io/beta
metadata:
  name: APIPolicies
  namespace: dev_all_san
  version: alphas
  tags:
    - one
    - two
    - three
    - sample
  type: REST
spec:
  api-spec:
    $path: 
      petstore.yaml
  policy-sequence:
    - $ref: dev_all:policyseq:1.0
